// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOG4sPNGdBkFrx90yA-yEOTNJwEwSRPZU',
    appId: '1:1085966356174:web:9c5fb1fe44978b2493ca9f',
    messagingSenderId: '1085966356174',
    projectId: 'chat-app-7ff3e',
    authDomain: 'chat-app-7ff3e.firebaseapp.com',
    storageBucket: 'chat-app-7ff3e.appspot.com',
    measurementId: 'G-KJ34CGN4KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2s72TcaZo84N2rLJdYM2KMF6TkGJOysU',
    appId: '1:1085966356174:android:e0b4c21da6fd2a3c93ca9f',
    messagingSenderId: '1085966356174',
    projectId: 'chat-app-7ff3e',
    storageBucket: 'chat-app-7ff3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA__ooiJ4TRzqh1ENBtZh1CswZpydJiA5o',
    appId: '1:1085966356174:ios:6f98f248cab9640493ca9f',
    messagingSenderId: '1085966356174',
    projectId: 'chat-app-7ff3e',
    storageBucket: 'chat-app-7ff3e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA__ooiJ4TRzqh1ENBtZh1CswZpydJiA5o',
    appId: '1:1085966356174:ios:6f98f248cab9640493ca9f',
    messagingSenderId: '1085966356174',
    projectId: 'chat-app-7ff3e',
    storageBucket: 'chat-app-7ff3e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOG4sPNGdBkFrx90yA-yEOTNJwEwSRPZU',
    appId: '1:1085966356174:web:6dd028ef175dd14693ca9f',
    messagingSenderId: '1085966356174',
    projectId: 'chat-app-7ff3e',
    authDomain: 'chat-app-7ff3e.firebaseapp.com',
    storageBucket: 'chat-app-7ff3e.appspot.com',
    measurementId: 'G-9KWR8XGT57',
  );
}
